import type { ModeId } from '@/modules/modes/modeTypes';

export interface AppTourStep {
  id: string;
  route: string;
  targetId?: string;
  modeId?: ModeId;
  title: string;
  description: string;
  eyebrow: string;
  placement?: 'top' | 'bottom';
}

export const APP_TOUR_STEPS: AppTourStep[] = [
  {
    id: 'welcome',
    route: '/',
    eyebrow: 'Blearn',
    title: 'Aus Reflex wird eine bewusste Entscheidung.',
    description: 'Blearn unterbricht Ablenkung nicht einfach – es schafft einen kurzen Moment für Fokus, Lernen oder eine bewusste Entscheidung.',
  },
  {
    id: 'navigation',
    route: '/',
    targetId: 'tour-bottom-nav',
    eyebrow: 'Orientierung',
    placement: 'top',
    title: 'Deine Bereiche auf einen Blick.',
    description: 'Hier wechselst du zwischen Fokus, Schutzregeln, Lernen, Fortschritt und Einstellungen.',
  },
  {
    id: 'home',
    route: '/',
    targetId: 'tour-dashboard-focus',
    eyebrow: 'Fokus',
    placement: 'top',
    title: 'Dein Überblick für heute.',
    description: 'Hier siehst du deine heutige Bildschirmzeit und kannst direkt in eine freiwillige Lernsession wechseln.',
  },
  {
    id: 'modes-selector',
    route: '/modes',
    eyebrow: 'Modi',
    title: 'Zielmodus auswählen.',
    description: 'Wähle hier, wie blockierte Apps später freigeschaltet werden.',
  },
  {
    id: 'modes-reflection',
    route: '/modes',
    targetId: 'tour-mode-reflection',
    modeId: 'strict',
    eyebrow: 'Reflexion',
    placement: 'top',
    title: 'Starte mit einem bewussten Moment.',
    description: 'Der Reflexionsmodus ist ausgewählt: Er unterbricht Ablenkung mit einem kurzen Moment zum Atmen und Entscheiden.',
  },
  {
    id: 'modes-reflection-settings',
    route: '/modes',
    targetId: 'tour-reflection-settings',
    modeId: 'strict',
    eyebrow: 'Reflexionsmodus',
    placement: 'top',
    title: 'Lege Runden und Freischaltzeit fest.',
    description: 'Diese Einstellungen gehören direkt zu deiner geöffneten Reflexionskarte: Lege Atemrunden und die Freischaltzeit fest.',
  },
  {
    id: 'modes-reflection-pattern',
    route: '/modes',
    targetId: 'tour-reflection-pattern',
    modeId: 'strict',
    eyebrow: 'Muster',
    placement: 'top',
    title: 'Wähle deinen Atemrhythmus.',
    description: 'Das Muster bestimmt, wie dich Blearn durch deine Reflexionsrunde führt.',
  },
  {
    id: 'modes-reflection-strict-addon',
    route: '/modes',
    targetId: 'tour-reflection-strict-addon',
    modeId: 'strict',
    eyebrow: 'Strikt-Zusatz',
    placement: 'top',
    title: 'Halte deine Regeln bei Bedarf fest.',
    description: 'Der Strikt-Zusatz schützt die Einstellungen deiner zugewiesenen Apps für das gewählte Zeitfenster.',
  },
  {
    id: 'modes-learn',
    route: '/modes',
    targetId: 'tour-mode-learn',
    modeId: 'learn',
    eyebrow: 'Learn',
    placement: 'top',
    title: 'Lernen kann Zeit freischalten.',
    description: 'Der Learn-Modus ist ausgewählt: Wiederhole deine Vokabeln, bevor du eine App bewusst weiter nutzt.',
  },
  {
    id: 'modes-learn-gate-settings',
    route: '/modes',
    targetId: 'tour-learn-gate-settings',
    modeId: 'learn',
    eyebrow: 'Freischalten',
    placement: 'top',
    title: 'Bestimme Vokabelanzahl und Freischaltzeit.',
    description: 'Diese Einstellungen gehören direkt zu deiner geöffneten Learn-Karte: Lege richtige Antworten und Freischaltzeit fest.',
  },
  {
    id: 'modes-learn-new-cards',
    route: '/modes',
    targetId: 'tour-learn-new-cards',
    modeId: 'learn',
    eyebrow: 'Neue Vokabeln',
    placement: 'top',
    title: 'Steuere den Abstand neuer Karten.',
    description: 'Entscheide, nach wie vielen Wiederholungen eine neue Vokabel in deine Lernsession kommt.',
  },
  {
    id: 'modes-learn-typed-answer',
    route: '/modes',
    targetId: 'tour-learn-typed-answer',
    modeId: 'learn',
    eyebrow: 'Eingabe',
    placement: 'top',
    title: 'Möchtest du Wörter eintippen?',
    description: 'Aktiviere die Eingabe, wenn du Antworten selbst schreiben möchtest. Ohne sie bewertest du deine Antwort direkt.',
  },
  {
    id: 'modes-penalty',
    route: '/modes',
    targetId: 'tour-mode-penalty',
    modeId: 'penalty',
    eyebrow: 'Strafmodus',
    title: 'Weiter zum Strafmodus.',
    description: 'Hier legst du eine bewusste Konsequenz für besonders wichtige Grenzen fest.',
  },
  {
    id: 'modes-lock',
    route: '/modes',
    targetId: 'tour-mode-lock',
    modeId: 'lock',
    eyebrow: 'Striktschutz',
    placement: 'top',
    title: 'Schütze ein festes Zeitfenster.',
    description: 'Der Striktschutz hält deine Regeln bis zum Ende des gewählten Zeitfensters verbindlich fest.',
  },
  {
    id: 'modes-lock-settings',
    route: '/modes',
    targetId: 'tour-lock-settings',
    modeId: 'lock',
    eyebrow: 'Striktschutz',
    placement: 'top',
    title: 'Lege Beginn und Ende fest.',
    description: 'Hier bestimmst du den Zeitraum, in dem deine Regeln und Einstellungen geschützt bleiben.',
  },
  {
    id: 'modes-targets',
    route: '/modes',
    targetId: 'tour-modes-blocking',
    eyebrow: 'Zuweisung',
    title: 'Jetzt kommen die echten Auslöser dazu.',
    description: 'Lege fest, welche Apps, Websites oder Suchen den gewählten Modus auslösen. Erst beim Speichern wird die Regel aktiv.',
  },
  {
    id: 'learn-hero',
    route: '/learn',
    eyebrow: 'Learn Hub',
    title: 'Lernen gehört dir.',
    description: 'Verwalte eigene Decks und starte tägliche Wiederholungen – auch ganz unabhängig von einem Schutzmodus.',
  },
  {
    id: 'learn-actions',
    route: '/learn',
    targetId: 'tour-learn-actions',
    eyebrow: 'Pakete',
    title: 'Deine Karten, dein Einstieg.',
    description: 'Öffne Decks, importiere Lernpakete oder erstelle eigene Inhalte – alles bleibt an einem Ort.',
  },
  {
    id: 'stats-overview',
    route: '/stats',
    eyebrow: 'Highlights',
    title: 'Deine Stats auf einen Blick.',
    description: 'Hier siehst du die wichtigsten Muster deiner Nutzung, Stimmung und deines Lernfortschritts.',
  },
  {
    id: 'stats-usage',
    route: '/stats?section=usage',
    targetId: 'tour-stats-usage',
    eyebrow: 'App-Nutzung',
    title: 'Wie du dein Smartphone nutzt.',
    description: 'Bildschirmzeit, Freischaltungen und deine meistgenutzten Apps zeigen dir deinen heutigen Verlauf.',
  },
  {
    id: 'stats-emotions',
    route: '/stats?section=emotions',
    targetId: 'tour-stats-emotions',
    eyebrow: 'Stimmung',
    title: 'Deine Stimmung im Verlauf.',
    description: 'Hier bündeln sich deine Check-ins: häufige Emotionen, ihr Verlauf und die letzten Einträge.',
  },
  {
    id: 'stats-vocab',
    route: '/stats?section=vocab',
    targetId: 'tour-stats-vocab',
    eyebrow: 'Lernen',
    title: 'Dein Lernfortschritt.',
    description: 'Behalte deine Wiederholungen, offenen Karten und die Entwicklung deiner Lernroutine im Blick.',
  },
  {
    id: 'settings',
    route: '/settings',
    eyebrow: 'Einstellungen',
    title: 'Alles bleibt anpassbar.',
    description: 'Passe Darstellung, Hinweise, Schutzoptionen und weitere Einstellungen jederzeit an deine Routine an.',
  },
];
